/*interface ORDER
//schwarzeVanille: string;
//sesamDattel: string;
//waldmeister: string;
//orangeZartbitter: string;
//minzeSchoko: string;
//latteMacchiato: string;
//granatapfel: string;
erdbeer: string;
schokolade: string;
vanille: string;
straciatella: string;
sahne: string;
streusel: string;
himbeersauce: string;
schokoladeWeissSauce: string;
schokoladensauce: string;
waffel: string;
becher: string;
}*/
//# sourceMappingURL=types.js.map